name: Mirror to GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/vermillio/sales-eng/metadata-api.git
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
